@startuml
'https://plantuml.com/class-diagram

class Controller
class enemy
class player
class panel
class frame
class combat{
ArrayList<CombatEntity> activeCombat
int combatRound

void startCombat()


}

combat *-- CombatEntity

class CombatEntity {
int hp
max hp
ArrayList<Cards> Deck
ArrayList<Cards> Hand

card takeTurn();


}


CombatEntity<|--enemy
CombatEntity<|--player
CombatEntity*--Card




abstract class Card{
int manaCost?
String type?




}







@enduml